FROM node:20-alpine AS builder
WORKDIR /app
COPY client/package*.json ./
RUN npm ci
COPY client/ .
RUN npm run build

FROM alpine
WORKDIR /app
COPY --from=builder /app/dist /app/dist
VOLUME /app/dist
CMD ["sh", "-c", "cp -r /app/dist/. /output/"]
